# Generated by Django 5.1.7 on 2025-03-20 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_monitor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoppedprocess',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_processes', to='process_monitor_app.storedprocess'),
        ),
    ]
