# Generated by Django 5.1.7 on 2025-03-17 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_monitor_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='start_Time',
            new_name='start_time',
        ),
    ]
