# Generated by Django 5.1.7 on 2025-03-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("process_monitor_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stoppedprocess",
            name="name",
            field=models.CharField(db_default="Unknow", max_length=200),
        ),
    ]
