# Generated by Django 5.1.7 on 2025-03-18 08:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_monitor_app', '0002_rename_start_time_process_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('PID', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('duration', models.FloatField()),
                ('memory_usage_MB', models.FloatField()),
                ('CPU_Usage_Percent', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='process',
            name='SnapShot',
        ),
        migrations.RemoveField(
            model_name='process',
            name='killed',
        ),
        migrations.AlterField(
            model_name='process',
            name='PID',
            field=models.IntegerField(db_index=True),
        ),
        migrations.CreateModel(
            name='StoppedProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=200)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stopped_processes', to='process_monitor_app.storedprocess')),
            ],
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='processes',
            field=models.ManyToManyField(related_name='snapshots', to='process_monitor_app.storedprocess'),
        ),
        migrations.DeleteModel(
            name='KilledProcess',
        ),
    ]
