# Generated by Django 5.1.7 on 2025-03-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_monitor_app', '0002_alter_stoppedprocess_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoppedprocess',
            name='process',
        ),
    ]
