# Generated by Django 5.1.7 on 2025-03-20 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_monitor_app', '0003_remove_stoppedprocess_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedprocess',
            name='StoppedProcess',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='stored_processes', to='process_monitor_app.stoppedprocess'),
            preserve_default=False,
        ),
    ]
